
/*
 EULER PROBLEM #2
 
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 
 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 
 */


func generateFib(limit: Int) -> [Int] {
  var state = (1,2)
  var returnArr = [state.0,state.1]
  var nextVal = state.0 + state.1
  
  repeat {
    returnArr.append(nextVal)
    state.0 = state.1
    state.1 = nextVal
    nextVal = state.0 + state.1
  } while nextVal < limit
  
  return returnArr
}

let evenFibs = generateFib(4_000_000).filter { $0 % 2 == 0 }
//let solution = evenFibs.reduce(0, combine: +)











